//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace paroquiaRussas.Utility.Resources {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Exceptions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Exceptions() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("paroquiaRussas.Utility.Resources.Exceptions", typeof(Exceptions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não foi possível enviar o email. Por favor tente novamente mais tarde..
        /// </summary>
        public static string EXC01 {
            get {
                return ResourceManager.GetString("EXC01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ocorreu um problema ao tentar encontrar evento..
        /// </summary>
        public static string EXC02 {
            get {
                return ResourceManager.GetString("EXC02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Erro ao recuperar evento por data..
        /// </summary>
        public static string EXC03 {
            get {
                return ResourceManager.GetString("EXC03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Erro ao adicionar evento..
        /// </summary>
        public static string EXC04 {
            get {
                return ResourceManager.GetString("EXC04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Erro ao editar evento..
        /// </summary>
        public static string EXC05 {
            get {
                return ResourceManager.GetString("EXC05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Erro ao excluir evento..
        /// </summary>
        public static string EXC06 {
            get {
                return ResourceManager.GetString("EXC06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não foi possível acessar a liturgia diária..
        /// </summary>
        public static string EXC07 {
            get {
                return ResourceManager.GetString("EXC07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Usuário ou senha inválidos..
        /// </summary>
        public static string EXC08 {
            get {
                return ResourceManager.GetString("EXC08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não foi possível efetuar login..
        /// </summary>
        public static string EXC09 {
            get {
                return ResourceManager.GetString("EXC09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não foi possível acessar as notícias..
        /// </summary>
        public static string EXC10 {
            get {
                return ResourceManager.GetString("EXC10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não foi possível recuperar o elemento pelo Id {0}..
        /// </summary>
        public static string EXC11 {
            get {
                return ResourceManager.GetString("EXC11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ocorreu um erro ao criar nova notícia..
        /// </summary>
        public static string EXC12 {
            get {
                return ResourceManager.GetString("EXC12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ocorreu um erro ao editar a notícia..
        /// </summary>
        public static string EXC13 {
            get {
                return ResourceManager.GetString("EXC13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ocorreu um erro ao deletar a notícia..
        /// </summary>
        public static string EXC14 {
            get {
                return ResourceManager.GetString("EXC14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ocorreu um erro ao recuperar os usuários.
        /// </summary>
        public static string EXC15 {
            get {
                return ResourceManager.GetString("EXC15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ocorreu um erro ao adicionar o usuário..
        /// </summary>
        public static string EXC16 {
            get {
                return ResourceManager.GetString("EXC16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ocorreu um erro ao deletar o usuário..
        /// </summary>
        public static string EXC17 {
            get {
                return ResourceManager.GetString("EXC17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ocorreu um erro ao tentar recuperar os eventos..
        /// </summary>
        public static string EXC18 {
            get {
                return ResourceManager.GetString("EXC18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ocorreu um erro ao recuperar o elemento pela data {0}.
        /// </summary>
        public static string EXC19 {
            get {
                return ResourceManager.GetString("EXC19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ocorreu um erro ao encontrar o usuário.
        /// </summary>
        public static string EXC20 {
            get {
                return ResourceManager.GetString("EXC20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não foi possível gerar um token corretamente..
        /// </summary>
        public static string EXC21 {
            get {
                return ResourceManager.GetString("EXC21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Invalide token..
        /// </summary>
        public static string EXC22 {
            get {
                return ResourceManager.GetString("EXC22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não foi possível gravar o token..
        /// </summary>
        public static string EXC23 {
            get {
                return ResourceManager.GetString("EXC23", resourceCulture);
            }
        }

        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Erro ao salvar imagem..
        /// </summary>
        public static string EXC24
        {
            get
            {
                return ResourceManager.GetString("EXC23", resourceCulture);
            }
        }
    }
}
